{% set name = "qcfractal" %}
{% set version = "0.15.8.1" %}
{% set sha256 = "89b85447df2b27e6ba6898a8cd226b5d8fbca026af97f3f3a057af580762f803" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - echo 'Keep lint happy'

outputs:
  - name: {{ name }}-core
    script: install.sh
    build:
      entry_points:
        - qcfractal-server = qcfractal.cli.qcfractal_server:main
        - qcfractal-manager = qcfractal.cli.qcfractal_manager:main
    requirements:
      host:
        - python
        - pip
      run:
        - python

        # Core dependencies
        - numpy >=1.17
        - msgpack-python >=0.6.1
        - tornado
        - requests
        - pyyaml >=5.1
        - pydantic >=1.4.0

        # Ecosystem dependencies
        - qcengine >=0.22
        - qcelemental >=0.24

        # Security dependencies
        - bcrypt
        - cryptography

        # Storage dependencies
        - sqlalchemy >=1.3,<1.4
        - alembic
        - psycopg2 >=2.7
        - postgresql

        # QCPortal dependencies
        - tqdm
        - pandas
        - h5py
        - pyarrow >=0.15.0
        - double-conversion >=3.0.0
    test:
      imports:
        - qcfractal

  - name: {{ name }}
    requirements:
      host:
        - python
        - pip
      run:
        - {{ pin_subpackage('qcfractal-core', max_pin='x.x.x') }}
        - plotly >=4.0.0
        - python >=3.7
    test:
      imports:
        - qcfractal

about:
  home: https://github.com/MolSSI/QCFractal
  dev_url: https://github.com/MolSSI/QCFractal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A distributed compute and database platform for quantum chemistry.

extra:
  recipe-maintainers:
    - lnaden
    - bennybp
